# Generated by Django 2.2.6 on 2019-12-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rich_text_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='desc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
    ]
