# Generated by Django 2.2.6 on 2019-12-24 10:30

from django.db import migrations
import index_auth_service.users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', index_auth_service.users.managers.CustomUserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
