# Generated by Django 2.2.6 on 2019-12-27 04:33

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='images/user_avatar_default.png', upload_to='user_avatars', verbose_name='User avatar'),
        ),
    ]
