# Generated by Django 2.2.6 on 2019-12-27 04:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='/static/images/user_avatar_default.png', upload_to='user_avatars', verbose_name='User avatar'),
        ),
    ]
