# Generated by Django 2.2.6 on 2019-12-27 04:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_change_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='user_avatars', verbose_name='User avatar'),
        ),
    ]
